export const wasteTypes = [
    'Altholz',
    'Altpapier',
    'Altreifen',
    'Asbesthaltige Abfälle',
    'Aschen',
    'Baumischabfälle',
    'Bauschutt',
    'Bodenmaterial (z.B. Baggergut)',
    'Brandabfall',
    'E-Schrott',
    'Gießereialtsand',
    'Kabelreste',
    'Klärschlamm',
    'Kunststoffabfälle',
    'PCB-haltige Abfälle',
    'Produktionsabfälle',
    'Schrott',
    'Siedlungsabfall',
    'Sperrmüll',
    'Spuckstoffe (Reste aus Papierfabriken)',
    'Steinkohlenasche',
    'teerhaltige Abfälle',
    'Textilien',
    'mineralische Abfälle',
    'ölhaltige Abfälle',
    'gefährliche Abfälle',
    'PFAS'
  ];